version: "3.9"
services:
  app:
    image: "ar1988/bt-backend:latest"
    container_name: bt-backend
    depends_on:
      - db
    environment:
      - SERVER_PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/business-tracker
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1234
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
    ports:
      - "8080:8080"
  db:
    image: postgres:latest
    container_name: bt-postgres
    environment:
      POSTGRES_DB: "business-tracker"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "1234"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./db_postgres/pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"
