version: "3.9"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: "business-tracker"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "1234"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - .:/var/lib/postgresql/data
    ports:
      - "5440:5432"
